import argparse
import os
import subprocess

# 4096x4096
# prompt_list = [
#     # First 50
#     "A high-resolution photograph of a single red rose with dewdrops on its velvety petals, set against a softly blurred dark green background, illuminated by gentle morning sunlight.",
#     "An ultra-detailed close-up of a vintage pocket watch revealing intricate gears and mechanisms, floating in a dark void with subtle light reflections highlighting its metallic surfaces.",
#     "A hyper-realistic rendering of a ripe green apple with a single leaf, placed on a rustic wooden table, bathed in warm, natural sunlight that casts soft shadows.",
#     "A macro shot of a monarch butterfly perched on a sunflower, wings spread wide displaying vivid orange and black patterns, with fine details of the flower's petals and the butterfly's antennae.",
#     "A high-definition image of a classic acoustic guitar leaning against a brick wall, with every string and wood grain clearly visible, under soft ambient lighting.",
#     "An ultra-detailed painting of a steaming cup of coffee on a saucer, with latte art forming a heart, surrounded by scattered coffee beans on a wooden surface.",
#     "A crystal-clear image of red wine being poured into a glass, capturing droplets and splashes frozen in mid-air against a clean white background.",
#     "A 3D rendering of a transparent glass sphere containing a miniature cityscape, floating above a reflective surface with subtle ambient lighting.",
#     "A high-resolution photograph of a golden retriever puppy sitting in a meadow, every strand of fur sharply defined, with a soft-focus background of wildflowers.",
#     "An ultra-detailed image of a shining diamond ring on black velvet, capturing all the facets, reflections, and subtle color dispersions of the diamond.",
#     "A hyper-realistic illustration of a single white feather floating mid-air, with intricate patterns and textures visible against a softly blurred background.",
#     "A detailed rendering of a vintage typewriter with a sheet of paper, keys and typebars visible, set in a dimly lit room with shadows adding depth.",
#     "A close-up photograph of a human eye reflecting a city skyline, the iris displaying intricate patterns and the city lights vividly captured.",
#     "A high-resolution image of a single red balloon floating in a clear blue sky, sunlight reflecting off its surface, creating a sense of whimsy.",
#     "A macro photograph of a honeybee collecting nectar from a lavender flower, wings in motion blur, with vivid colors and fine details.",
#     "A detailed rendering of a pirate's treasure chest overflowing with gold coins and jewels, set on a sandy beach with the ocean in the background.",
#     "A hyper-realistic image of a stack of old books with worn covers, placed on a wooden shelf, with dust particles visible in the warm light.",
#     "A high-definition close-up of a ripe strawberry, seeds and surface texture clearly visible, set against a simple white background.",
#     "A detailed illustration of a violin resting on sheet music, with warm lighting highlighting the rich wood grain and curved shape.",
#     "A high-resolution image of a single snowflake on a dark background, showing its intricate crystal structure in astonishing detail.",
#     "A close-up photograph of a lit light bulb hanging in a dark room, with filaments glowing brightly and subtle reflections on the glass surface.",
#     "An ultra-detailed rendering of a spaceship floating in space, with intricate surface details and a backdrop of stars and distant galaxies.",
#     "A hyper-realistic image of a steaming bowl of ramen, chopsticks resting on the bowl, showcasing noodles, broth, and toppings in vivid detail.",
#     "A high-definition photograph of a majestic lion's face, mane and whiskers sharply in focus, eyes gazing intensely into the camera.",
#     "A detailed illustration of an ancient key lying on a stone surface, showing intricate designs and rusted metal textures under moody lighting.",
#     "A macro shot of water droplets on a leaf after rain, capturing reflections and the leaf's textured surface with a softly blurred background.",
#     "A high-resolution image of a colorful parrot perched on a branch, feathers and patterns vividly displayed against a tropical backdrop.",
#     "A detailed rendering of a vintage compass pointing north, placed on an old map with warm ambient lighting highlighting its metallic finish.",
#     "A close-up photograph of a chessboard mid-game, focusing on the queen piece with shallow depth of field blurring the background pieces.",
#     "A hyper-realistic image of a fresh orange sliced in half, showing juicy pulp and texture against a clean white background.",
#     "A high-definition illustration of a glowing crystal orb floating above a pedestal, set in a dark, mystical environment with swirling mists.",
#     "A detailed photograph of a steaming locomotive on tracks, with smoke billowing realistically and intricate details of the engine visible.",
#     "A macro shot of a ladybug on a blade of grass, dew drops present, with a softly blurred natural background.",
#     "A high-resolution image of a pair of ballet shoes hanging by their ribbons, against a softly lit background that hints at a dance studio.",
#     "A detailed rendering of a futuristic robotic hand holding a delicate flower, showcasing metallic textures and intricate mechanical parts.",
#     "A hyper-realistic image of a chocolate bar being broken apart, with nuts and caramel visible inside, against a simple backdrop.",
#     "A close-up photograph of a burning candle in a dark room, capturing the flame's movement and melting wax in exquisite detail.",
#     "A high-definition image of a sailboat silhouetted against a vibrant sunset, with reflections on the water and dramatic sky colors.",
#     "A detailed illustration of a dragonfly hovering over a pond, wings and body intricately detailed, with water reflections below.",
#     "A macro photograph of a chameleon's eye, showing textured skin and detailed patterns in vivid colors.",
#     "A high-resolution rendering of a medieval knight's helmet, displaying scratches and dents, set against a stark black background.",
#     "A close-up image of a vinyl record spinning on a turntable, with grooves and the needle in sharp focus under warm lighting.",
#     "A hyper-realistic photograph of a glass chess set under dramatic lighting, highlighting reflections and transparency of the pieces.",
#     "A detailed rendering of a futuristic cityscape inside a snow globe, with tiny buildings and falling snowflakes, set against a dark backdrop.",
#     "A high-definition image of a majestic eagle in flight, wings spread wide with feathers detailed, soaring against a clear blue sky.",
#     "A macro shot of coffee beans piled together, showing textures and rich brown tones, with a rustic background.",
#     "A detailed photograph of an hourglass with sand flowing, placed on a reflective surface in a dimly lit room, capturing time's passage.",
#     "A high-resolution image of a classic car dashboard, with gauges and dials illuminated, showcasing vintage details.",
#     "A hyper-realistic rendering of a single oak leaf floating on still water, with reflections and gentle ripples emanating outward.",
#     "A detailed illustration of a treasure map spread out on a wooden table, with a compass and magnifying glass beside it, lit by candlelight.",
#     # Second 50
#     "An ultra-detailed close-up of a vintage fountain pen resting on an open notebook, with ink droplets forming on the nib under soft ambient light.",
#     "A high-definition image of a colorful hot air balloon soaring over mountains, with intricate patterns on the balloon's fabric vividly displayed.",
#     "A hyper-realistic rendering of a single maple leaf in autumn, showing vibrant red and orange hues, with veins and textures in sharp focus.",
#     "A detailed photograph of a steaming cup of herbal tea with a lemon slice, set on a windowsill with raindrops on the glass behind.",
#     "A macro shot of a snail on a wet leaf, with the shell's spiral pattern and the snail's antennae sharply detailed.",
#     "An ultra-detailed rendering of a futuristic smartwatch interface, hovering above the watch's surface, showcasing holographic elements.",
#     "A high-resolution image of a stack of pancakes drizzled with syrup, topped with fresh berries, captured in mouth-watering detail.",
#     "A detailed illustration of a classic sailing ship in a bottle, with sails fully unfurled and miniature ocean waves.",
#     "A hyper-realistic photograph of a single raindrop on a spider's web, capturing reflections and the delicate strands of the web.",
#     "A close-up image of a hand holding a delicate origami crane, with fine details of the folded paper visible.",
#     "A high-definition rendering of a gleaming motorcycle engine, showcasing chrome details and mechanical intricacies under studio lighting.",
#     "A detailed photograph of a vintage camera, with focus on the lens and aperture blades, set against a blurred background.",
#     "An ultra-detailed image of a chess knight piece made of marble, placed on a chessboard with other pieces out of focus.",
#     "A macro shot of fresh blueberries covered in morning dew, with textures and rich colors vividly captured.",
#     "A high-resolution illustration of a quill pen writing on parchment, with ink flowing and cursive script forming on the paper.",
#     "A detailed rendering of a mechanical pocket watch with transparent casing, revealing gears and springs in motion.",
#     "A hyper-realistic image of a golden key suspended in mid-air, with intricate designs and a glowing aura, set against a dark background.",
#     "A close-up photograph of a sand timer with sand grains flowing, capturing motion and the clarity of the glass.",
#     "An ultra-detailed image of a violin scroll and tuning pegs, highlighting wood grain and craftsmanship under warm lighting.",
#     "A high-definition rendering of a dragon's eye, with scales and fiery reflections, set against a shadowy backdrop.",
#     "A detailed photograph of a colorful kite flying against a cloudy sky, with the tail ribbons flowing in the wind.",
#     "A macro shot of a peacock feather, showing iridescent colors and fine barbs in exquisite detail.",
#     "A hyper-realistic image of a glass of lemonade with ice cubes and mint leaves, condensation droplets visible on the glass.",
#     "A close-up rendering of a spaceship cockpit's control panel, with buttons, screens, and holographic displays illuminated.",
#     "A high-resolution image of a bonsai tree in a ceramic pot, capturing the twisted branches and delicate leaves.",
#     "A detailed illustration of a set of colorful dice rolling across a table, with numbers and edges sharply defined.",
#     "An ultra-detailed photograph of a magnifying glass enlarging text on a page, with the lens and text in sharp focus.",
#     "A macro shot of a lady's wristwatch with diamond accents, showcasing the timepiece's elegance and craftsmanship.",
#     "A hyper-realistic rendering of a glass bottle with a ship inside, capturing the miniature details of the ship and reflections on the glass.",
#     "A close-up image of a harp's strings and wooden frame, highlighting the craftsmanship and golden tuning pegs.",
#     "A high-definition photograph of a sunflower field focusing on a single bloom, with petals and center details in sharp focus.",
#     "A detailed rendering of an old-fashioned lantern glowing in the dark, with intricate metalwork and warm light emanating.",
#     "An ultra-detailed image of a single snow-covered pinecone, textures and frost crystals clearly visible against a blurred background.",
#     "A macro photograph of a pencil tip writing on paper, with graphite marks and paper texture in sharp detail.",
#     "A hyper-realistic image of a ripe banana peeled halfway, showing the texture of the fruit and the peel.",
#     "A close-up rendering of a medieval shield with a family crest, displaying detailed engravings and weathered textures.",
#     "A high-resolution image of a seahorse swimming underwater, with delicate features and tiny bubbles captured.",
#     "A detailed photograph of a set of colored pencils arranged in a circle, tips pointing inward, showing wood grain and pigments.",
#     "An ultra-detailed illustration of a futuristic drone hovering, with rotors in motion and metallic body reflecting light.",
#     "A macro shot of a cat's paw touching a glass surface, with fur and claws in focus and paw prints visible.",
#     "A hyper-realistic rendering of a crystal wine glass half-filled, capturing reflections and refractions of light.",
#     "A close-up photograph of a vinyl record's grooves, with the needle in place and subtle reflections on the vinyl surface.",
#     "A high-definition image of a feather quill dipped in an inkpot, with ink droplets and antique desk setting.",
#     "A detailed rendering of a carousel horse with ornate decorations, set against a blurred amusement park background.",
#     "An ultra-detailed image of a seashell held up against the sun, with light shining through and textures visible.",
#     "A macro photograph of a small frog sitting on a lily pad, with water droplets and reflections captured.",
#     "A hyper-realistic image of a single slice of watermelon, showing seeds and juicy textures in vibrant colors.",
#     "A close-up rendering of a knight's gauntlet holding a sword hilt, with metal textures and engravings detailed.",
#     "A high-resolution image of an astronaut's helmet reflecting Earth, capturing the helmet's details and the reflection clearly.",
#     "A detailed illustration of a violin bow drawing across strings, with motion blur on the bow hairs and instrument details.",
#     # Third 50
#     "An ultra-detailed photograph of a model airplane in flight, with propellers spinning and landscape blurred below.",
#     "A macro shot of a honeycomb dripping with honey, capturing the geometric patterns and golden hues.",
#     "A hyper-realistic rendering of a glass marble with swirling colors inside, resting on a reflective surface.",
#     "A close-up image of a guitar pick between strings, highlighting the textures of the pick and strings.",
#     "A high-resolution illustration of a compass rose on aged parchment, with detailed markings and compass points.",
#     "A detailed photograph of a feather caught in a spider's web, with fine details of both the feather and web.",
#     "An ultra-detailed image of a single light bulb illuminating a dark room, with the filament glowing and glass reflections.",
#     "A macro shot of a snowdrop flower emerging through snow, capturing delicate petals and surrounding frost.",
#     "A hyper-realistic image of a rowboat floating on calm waters, with reflections and ripples detailed.",
#     "A close-up rendering of a typewriter key being pressed, with mechanical parts and letters in focus.",
#     "A high-resolution image of a stack of colorful macarons, showcasing textures and pastel hues.",
#     "A detailed illustration of a medieval scroll unrolled on a table, with ancient writing and symbols.",
#     "An ultra-detailed photograph of a bicycle's gear and chain, highlighting metallic textures and grease marks.",
#     "A macro shot of a chessboard with glass pieces, capturing reflections and transparency under dramatic lighting.",
#     "A hyper-realistic rendering of a single droplet of water splashing, frozen in time against a dark background.",
#     "A close-up image of a hand holding a glowing orb, with light emanating from the orb and illuminating the hand.",
#     "A high-definition photograph of a flamingo standing in water, with pink feathers and reflection captured.",
#     "A detailed rendering of a space shuttle launching, with smoke, flames, and detailed textures of the shuttle.",
#     "An ultra-detailed image of a daisy against a blue sky, with petals and center in sharp focus.",
#     "A macro shot of a vintage keyhole, with the surrounding wood grain and metal details in sharp focus.",
#     "A hyper-realistic image of a glass teapot with blooming tea inside, capturing steam and delicate flower details.",
#     "A close-up rendering of a vinyl record album cover art, with vivid colors and textures of the printed material.",
#     "A high-resolution image of a fox's face peering through foliage, with sharp focus on eyes and fur.",
#     "A detailed illustration of a magnolia blossom in full bloom, capturing the softness and color gradients of the petals.",
#     "An ultra-detailed photograph of a neon sign glowing in the night, with reflections on wet pavement below.",
#     "A macro shot of a bee's wings as it hovers near a flower, capturing motion and wing details.",
#     "A hyper-realistic rendering of a gemstone reflecting light, showing facets and internal reflections.",
#     "A close-up image of a musician's hands playing the piano, with keys and hands in sharp focus.",
#     "A high-definition illustration of a hot cup of cocoa with marshmallows, steam rising and chocolate shavings on top.",
#     "A detailed photograph of a vintage telephone with rotary dial, capturing details of the handset and cord.",
#     "An ultra-detailed image of a single autumn leaf floating on water, with ripples and reflections.",
#     "A macro shot of a fresh green pea pod opened, revealing peas inside and textures of the pod.",
#     "A hyper-realistic image of a lighthouse standing against stormy seas, with waves crashing and light beam visible.",
#     "A close-up rendering of an artist's palette with mixed paints, textures of the paint and brush strokes detailed.",
#     "A high-resolution image of a paper airplane mid-flight, with motion blur and blue sky background.",
#     "A detailed illustration of a knight's chess piece carved from wood, showing grain and intricate carving.",
#     "An ultra-detailed photograph of an hourglass with colored sand, capturing motion and the clarity of the glass.",
#     "A macro shot of a single grain of sand under magnification, revealing textures and crystalline structures.",
#     "A hyper-realistic rendering of a book with pages turning, capturing motion and paper textures.",
#     "A close-up image of a single candle flame in darkness, with smoke wisps and melting wax detailed.",
#     "A high-definition photograph of a rainbow reflected in a soap bubble, capturing colors and surface tension.",
#     "A detailed rendering of a futuristic city skyline at night, with illuminated buildings and flying vehicles.",
#     "An ultra-detailed image of a piano's internal strings and hammers, showcasing mechanical intricacies.",
#     "A macro shot of a raindrop hitting a puddle, capturing the splash and concentric ripples.",
#     "A hyper-realistic image of a quill writing in the air, with letters forming and ink particles visible.",
#     "A close-up rendering of a dragon's scale armor, with metallic sheen and intricate patterns.",
#     "A high-resolution image of a jellyfish floating underwater, with translucent body and tentacles detailed.",
#     "A detailed photograph of a spinning top mid-spin, capturing motion blur and surface details.",
#     "An ultra-detailed image of a single oak leaf with morning frost, showing crystals and leaf veins.",
#     "A macro shot of a ladybug's wings opening, with colors and textures captured in exquisite detail."
# ]


# 2048x4096
# prompt_list = [
#     # First 50
#     "A towering futuristic cityscape at night, with skyscrapers reaching into the clouds, illuminated by neon lights and holographic advertisements, flying cars zipping between the buildings under a starry sky.",
#     "An ancient, mystical tree in a dense forest, its massive roots and branches twisting upwards, adorned with glowing lanterns and surrounded by ethereal creatures, with rays of sunlight filtering through the canopy.",
#     "A majestic waterfall cascading down a rugged cliff, surrounded by lush greenery and vibrant flowers, with a rainbow forming in the mist and exotic birds soaring above.",
#     "A detailed portrait of a medieval knight in ornate armor, standing tall with a sword planted in the ground, set against a backdrop of a stormy battlefield with distant lightning.",
#     "A vertical panoramic view of a deep canyon, showing layered rock formations, a winding river at the bottom, and a suspension bridge connecting the two sides, with hikers crossing.",
#     "An astronaut floating above Earth, tethered to a spacecraft, with the curvature of the Earth below and a backdrop of stars, nebulae, and the Milky Way stretching upwards.",
#     "A skyscraper-sized robot standing in a modern city, towering over buildings, with people looking up in awe, and clouds drifting around its head.",
#     "A traditional Japanese pagoda rising above cherry blossom trees, petals gently falling, with a serene mountain range and a setting sun in the background.",
#     "A tall lighthouse perched on a cliff edge, waves crashing below, the light beam cutting through a foggy night sky, guiding ships in the distance.",
#     "A giant sequoia tree with a carved-out tunnel, cars driving through its base, tourists taking photos, and the tree's immense height disappearing into the canopy.",
#     "An elegant ballerina leaping gracefully in mid-air, her dress flowing, set against a minimalist studio backdrop with high ceilings and tall windows.",
#     "A rocket launching into space, flames and smoke billowing out, the rocket ascending towards the top of the frame against a clear blue sky.",
#     "A medieval castle tower, with ivy climbing up the stone walls, banners fluttering in the wind, and a dragon perched at the top, overlooking a vast landscape.",
#     "An underwater scene looking up towards the surface, schools of colorful fish swimming, rays of sunlight penetrating the water, and a diver exploring a coral reef.",
#     "A towering iceberg floating in the ocean, with intricate patterns in the ice, penguins standing on ledges, and the aurora borealis lighting up the night sky.",
#     "A vertical garden skyscraper, covered in plants and trees, with terraces and balconies, set in a modern eco-friendly cityscape.",
#     "A mystical wizard's tower, spiraling upwards with glowing runes, surrounded by swirling clouds and magical energy emanating from the top.",
#     "A soaring eagle in flight, wings fully extended, flying over a vast canyon with the landscape stretching out below.",
#     "A detailed close-up of a skyscraper under construction, cranes lifting steel beams, workers in safety gear, and the city skyline in the background.",
#     "An ancient Mayan pyramid rising above the jungle canopy, with mist shrouding the base, and the sun breaking through clouds above.",
#     "A high-fashion model in an avant-garde outfit, posing dramatically against a stark urban backdrop with graffiti-covered walls and towering buildings.",
#     "A towering sand dune in the desert, with a lone traveler climbing towards the peak, the sun setting and casting long shadows across the sands.",
#     "A vertical cross-section of a deep-sea trench, showing various marine life at different depths, from surface dwellers to bioluminescent creatures in the abyss.",
#     "A monumental statue carved into a mountain, reminiscent of Mount Rushmore, but depicting ancient deities with intricate details and lush vegetation surrounding.",
#     "A skyscraper-sized waterfall on an alien planet, with unusual rock formations, strange vegetation, and multiple moons visible in the sky.",
#     "A grand cathedral interior, with towering stained-glass windows, vaulted ceilings adorned with frescoes, and sunlight streaming through.",
#     "A hot air balloon ascending into the sky, with a panoramic view of patchwork fields below and other balloons in the distance, set during sunrise.",
#     "An enormous treehouse complex, built among giant trees, connected by rope bridges, with people walking along and lanterns glowing from windows.",
#     "A spiral staircase in a modern art museum, with people ascending and descending, and abstract art pieces displayed along the tall walls.",
#     "A rocket towering on a launch pad, surrounded by scaffolding, engineers preparing for launch, and clouds in the sky reflecting the early morning light.",
#     "A climber scaling a steep mountain face, with snow-capped peaks around, clouds below, emphasizing the height and challenge.",
#     "A vertical garden inside a futuristic mall, with multiple levels of shops, waterfalls cascading down, and natural light from a glass ceiling.",
#     "A towering wave about to crash, surfers riding the wave, the sun shining through the translucent water, capturing the power of the ocean.",
#     "An ancient library with towering bookshelves, ladders reaching up to higher levels, and light filtering in from high windows creating a warm glow.",
#     "A skyscraper with a reflective glass facade, capturing the cityscape and clouds, with birds flying by and the sun setting.",
#     "A majestic giraffe standing tall in the savannah, with acacia trees and a vibrant sunset backdrop, other wildlife visible in the distance.",
#     "An enchanted beanstalk growing into the clouds, with a tiny figure climbing it, and mysterious lands visible above the cloud layer.",
#     "A city street with towering billboards and neon signs, pedestrians bustling below, capturing the energy of a metropolis like Tokyo at night.",
#     "A narrow alleyway between tall buildings, with hanging lanterns, shop signs, and a glimpse of the starry sky above.",
#     "A vertical panorama of a grand canyon, showing layers of geological strata, with a river at the bottom and a clear blue sky above.",
#     "An artistic rendition of DNA strands spiraling upwards, with glowing elements and scientific symbols floating around.",
#     "A space elevator stretching from Earth into space, with climbers ascending, and celestial bodies like the moon and stars in the background.",
#     "A giant waterfall flowing from floating islands, suspended in the sky, with airships navigating around them and clouds swirling.",
#     "A high-rise apartment building with colorful balconies, residents engaged in various activities, creating a mosaic of urban life.",
#     "An ancient temple carved into a cliff face, with steps leading up, monks ascending, and prayer flags fluttering in the wind.",
#     "A massive tree with homes built into it, like an elven village, with bridges connecting branches and lights glowing from windows at night.",
#     "A rocket trail streaking upwards through clouds, the rocket itself already out of sight, leaving a dramatic plume across the sky.",
#     "A skyscraper with a rooftop garden, people enjoying the greenery, with the city stretching out below under a twilight sky.",
#     "A vertical landscape of a mountain reflected in a lake, creating a symmetrical image from top to bottom, with autumn foliage.",
#     "An artist's loft with large windows, sunlight streaming in, canvases and art supplies scattered around, and a view of the city skyline.",
#     # Second 50
#     "A spiral galaxy rendered vertically, with stars and cosmic dust swirling towards the center, vivid colors against the darkness of space.",
#     "A tall ship with sails unfurled, masts reaching high, sailing towards the horizon under a dramatic sky with rays of sunlight breaking through clouds.",
#     "A bustling vertical market, with multiple levels connected by stairs and elevators, vendors selling various goods, and a glass ceiling above.",
#     "A climber hanging from a vertical ice wall, using ice axes, with icy peaks surrounding and a clear sky overhead.",
#     "An ornate clock tower rising above a historic city, clock face showing time, pigeons flying around, and cobblestone streets below.",
#     "A tall waterfall in a tropical rainforest, with lush vegetation, exotic birds, and mist filling the air, sunlight filtering through the canopy.",
#     "A skyscraper under construction at night, illuminated by floodlights, with cranes and workers silhouetted against the city lights.",
#     "A series of hot air balloons ascending in the early morning, with fog rolling over the landscape below, mountains in the distance.",
#     "An ancient lighthouse guiding ships, waves crashing below, stars twinkling above, and a ship approaching in the distance.",
#     "A futuristic vertical farm inside a skyscraper, layers of crops growing under artificial lights, workers tending to plants, robots assisting.",
#     "A mountain climber reaching the summit, arms raised in triumph, with a panoramic view of the mountain range and clouds below.",
#     "An underwater kelp forest, tall kelp reaching towards the surface, schools of fish swimming among them, sunlight filtering down.",
#     "A vertical shot of a suspension bridge, cables stretching upwards, cars and pedestrians crossing, city skyline in the background.",
#     "An astronaut descending onto the surface of Mars, spacecraft hovering above, red landscape stretching out, distant mountains.",
#     "A tall totem pole carved with intricate designs, set against a backdrop of mountains and forest, with cultural symbols.",
#     "A vertical cross-section of a skyscraper, showing different floors with various activities, from offices to gyms to restaurants, elevators moving.",
#     "A giant clock tower in a steampunk city, gears and cogs visible, steam rising from pipes, airships flying around.",
#     "A majestic redwood forest, with towering trees, sunlight filtering through, and a carpet of ferns and wildflowers below.",
#     "A mountain waterfall turning into clouds, blending seamlessly with the sky, creating a surreal image of nature and atmosphere.",
#     "An angel statue reaching towards the heavens, wings spread, clouds and rays of sunlight above, a sense of serenity.",
#     "A vertical city built into the side of a cliff, with homes and pathways carved into the rock, lights glowing at dusk.",
#     "A rocket launching from an ocean platform, water splashing, flames roaring, and the rocket ascending into the sky.",
#     "A vertical shot of an indoor rock climbing wall, climbers at various heights, colorful holds dotting the wall, skylights above.",
#     "A tall modern art sculpture in a plaza, people gathered around, buildings in the background, capturing urban culture.",
#     "A time-lapse image of stars forming circular trails above a mountain, capturing the rotation of the Earth in a vertical frame.",
#     "A vertical garden wall on a building exterior, covered in various plants and flowers, adding greenery to the urban environment.",
#     "A lighthouse in a storm, lightning striking in the background, waves crashing dramatically, the beacon shining bright.",
#     "A skyscraper with a glass elevator ascending the exterior, offering panoramic views of the city, people inside taking photos.",
#     "An ancient tower covered in vines, with a mysterious glow emanating from the top window, birds flying around.",
#     "A vertical forest, skyscrapers with trees growing on every floor, blending architecture and nature seamlessly.",
#     "A kite flying high in the sky, string held by a child below, clouds drifting by, capturing a moment of joy.",
#     "A monumental statue of a figure holding a torch, reminiscent of the Statue of Liberty, with the city below and sky above.",
#     "A city street viewed from below, tall buildings on either side, with the sky framed at the top, birds flying overhead.",
#     "A vertical slice of Earth's layers, from the crust to the core, illustrating geological strata and underground features, including caves and magma.",
#     "A hot air balloon festival, dozens of balloons ascending, filling the sky with colors against a backdrop of mountains.",
#     "A skyscraper with a rooftop swimming pool, people swimming, with glass walls showing the city below, sunset reflecting on the water.",
#     "A tall sailing ship docked at a harbor, masts and rigging detailed, with a bustling port around, seagulls flying.",
#     "An elevator shaft inside a modern building, looking up towards the top, cables and mechanical elements visible, lights illuminating the way.",
#     "A vertical garden with a waterfall inside a hotel atrium, guests walking along balconies overlooking the scene, plants cascading down.",
#     "A narrow canyon with sunlight streaming in from above, hikers exploring the depths, walls adorned with ancient petroglyphs.",
#     "A high-speed train moving through a mountainous landscape, tunnels and bridges, emphasizing vertical elements, clouds brushing peaks.",
#     "A futuristic skyscraper with wind turbines integrated, harnessing renewable energy, with clouds moving past, sun shining.",
#     "A diving board extending over a high cliff, a diver mid-jump, ocean far below, capturing a sense of adventure.",
#     "A vertical cityscape reflected in a puddle, creating a mirrored effect from top to bottom, rain just subsided.",
#     "An enormous statue of a deity in a temple, worshippers gathered below, incense smoke rising, intricate carvings.",
#     "A giant sequoia tree with a spiral staircase built around it, allowing visitors to ascend, canopy above, forest floor below.",
#     "A tall waterfall flowing over terraced steps, with greenery and flowers on each level, a rainbow forming in the mist.",
#     "A vertical view of an indoor shopping mall, multiple floors connected by escalators, skylight at the top, shoppers moving about.",
#     "An aerial silks performer hanging from a tall ceiling, fabric flowing, pose captured mid-movement, spotlight highlighting.",
#     "A majestic mountain peak piercing through clouds, with the sun rising behind, casting golden light, climbers reaching the summit.",
# ]

# 1280x1280
# prompt_list = [
#     "A tranquil beach scene at sunrise, with gentle waves lapping against the shore, seashells scattered on the sand, and a lone palm tree leaning over the water.",
#     "An astronaut planting a flag on the surface of the moon, Earth visible in the sky behind, stars sparkling in the dark expanse of space.",
#     "A bustling city street in the rain, with people holding colorful umbrellas, reflections of neon signs on wet pavement, and taxis splashing through puddles.",
#     "A serene countryside landscape with rolling green hills, a winding river, a stone bridge, and a herd of sheep grazing under a cloudy sky.",
#     "A close-up of a butterfly perched on a blooming flower, wings spread wide displaying intricate patterns and vibrant colors, with a soft-focus background.",
#     "An ancient library filled with towering bookshelves, ladders on wheels, golden light streaming through stained-glass windows, and dust particles floating in the air.",
#     "A futuristic space station orbiting a distant planet, with sleek spacecraft docking, astronauts in space suits conducting repairs, and galaxies visible in the background.",
#     "A group of children flying kites in an open field, the sky filled with kites of various shapes and colors, and a gentle breeze blowing.",
#     "A serene lake surrounded by autumn foliage, with vibrant reds, oranges, and yellows reflected in the calm water, and a small wooden rowboat tied to a dock.",
#     "A desert landscape with towering sand dunes, a caravan of camels led by nomads, and a setting sun casting long shadows across the sands.",
#     "A classic steamship sailing on a calm ocean, with white sails billowing in the wind, seagulls flying overhead, and a distant coastline visible.",
#     "A modern kitchen interior with a chef preparing a gourmet meal, fresh ingredients laid out on the countertop, and stainless steel appliances gleaming.",
#     "A rainforest scene with a waterfall cascading into a pool, exotic birds perched on branches, and lush green vegetation surrounding the area.",
#     "A street market in an Asian city, with vendors selling spices and textiles, colorful lanterns hanging overhead, and a crowd of shoppers browsing.",
#     "A serene mountain lake at dawn, with mist rising from the water, pine trees lining the shore, and a lone fisherman casting a line from a canoe.",
#     "A detailed close-up of a violin resting on sheet music, with the warm glow of candlelight reflecting off the polished wood.",
#     "A high-energy sports scene capturing a basketball player mid-air performing a slam dunk, with the crowd cheering in the background.",
#     "A historical battlefield scene with soldiers in uniform charging forward, cannons firing, and smoke enveloping the landscape.",
#     "A peaceful Zen garden with meticulously raked sand patterns, smooth stones, and a traditional Japanese tea house in the background.",
#     "A vibrant carnival at night, with a Ferris wheel illuminated against the sky, colorful game booths, and people enjoying cotton candy and laughter.",
#     "A futuristic underwater city with glass-domed structures, marine life swimming around, and people walking through transparent tunnels.",
#     "A majestic eagle soaring over a mountain range, wings spread wide, with snow-capped peaks and a clear blue sky as the backdrop.",
#     "A cozy reading nook by a window on a rainy day, with a comfortable chair, a stack of books, a steaming cup of tea, and raindrops on the glass.",
#     "An artist's studio filled with canvases, paint splatters on the floor, brushes in jars, and a large window letting in natural light.",
#     "A space shuttle re-entering Earth's atmosphere, fiery glow surrounding the craft, with the curvature of the Earth and clouds below.",
#     "A medieval blacksmith working at his forge, sparks flying as he hammers glowing metal, and tools hanging on the walls.",
#     "A group of penguins waddling across an icy landscape, with icebergs in the background and a soft pink sunrise.",
#     "A serene Buddhist temple set on a mountain cliff, prayer flags fluttering in the wind, and monks in saffron robes meditating.",
#     "A close-up of a classic car's dashboard, showcasing vintage gauges, a wooden steering wheel, and chrome accents.",
#     "A vibrant underwater coral reef scene with a sea turtle gliding past, schools of colorful fish, and sunlight filtering down.",
#     "A bustling train station from the early 20th century, with steam locomotives, passengers in period attire, and porters carrying luggage.",
#     "A science fiction scene of a colony on Mars, with domed habitats, astronauts in suits exploring the terrain, and distant mountains.",
#     "A peaceful vineyard at harvest time, rows of grapevines stretching into the distance, workers picking grapes, and a farmhouse on a hill.",
#     "A close-up of a person's hands knitting a colorful scarf, with yarn balls and knitting needles in view.",
#     "A snowy village during the holidays, with decorated houses, children building a snowman, and softly falling snow.",
#     "A majestic whale breaching the ocean surface, water spraying, with a dramatic sky and distant horizon.",
#     "A bustling cafe in a European city, people sitting at outdoor tables, cobblestone streets, and historic buildings in the background.",
#     "An enchanted castle floating in the clouds, with waterfalls cascading off the edges, and dragons flying around.",
#     "A close-up of an old compass resting on an ancient map, with a magnifying glass and notes scribbled in the margins.",
#     "A high-speed train passing through a futuristic cityscape at night, neon lights reflecting off its sleek surface.",
#     "A peaceful garden with a koi pond, lily pads floating, colorful fish swimming below the surface, and a small wooden bridge.",
#     "A dynamic dance performance on stage, with dancers in colorful costumes mid-leap, and dramatic lighting highlighting their movements.",
#     "A forest in springtime, with cherry blossoms in full bloom, petals drifting through the air, and sunlight filtering through the branches.",
#     "A detailed illustration of a fantasy tavern filled with adventurers, a roaring fireplace, and maps and weapons adorning the walls.",
#     "A dramatic seascape with towering waves crashing against rocky cliffs, storm clouds overhead, and a lighthouse standing resilient.",
#     "A bustling market street in a Middle Eastern city, with spice stalls, textile merchants, ornate architecture, and people in traditional attire.",
#     "A serene field of lavender in full bloom, stretching to the horizon, with a clear blue sky and distant mountains.",
#     "An aerial view of a complex maze made of tall hedges, with people navigating the paths and a central fountain.",
#     "A detailed steampunk airship floating above the clouds, with gears and pipes visible, and crew members on deck.",
#     "A tranquil sunset over a calm ocean, with sailboats silhouetted against the vibrant colors of the sky.",
#     # Second 50
#     "A high-energy rock concert scene, with a guitarist performing on stage, spotlights, and an enthusiastic crowd.",
#     "A rustic bakery interior with fresh bread and pastries displayed, a brick oven in the background, and the baker at work.",
#     "A close-up of a snow leopard in a mountainous terrain, its fur blending with the snowy background, and piercing blue eyes.",
#     "A futuristic robot companion helping a child with homework at a kitchen table, with a modern home interior.",
#     "An epic space battle scene with starships exchanging laser fire, explosions, and planets visible in the distance.",
#     "A tranquil scene of a hot air balloon festival at sunrise, with colorful balloons filling the sky over rolling hills.",
#     "A historical scene of a steam-powered paddleboat cruising down the Mississippi River, with passengers enjoying the view.",
#     "A detailed illustration of a mythical phoenix rising from ashes, wings ablaze, and flames swirling around.",
#     "A serene beach at night with bioluminescent waves glowing, stars reflected in the water, and a campfire on the shore.",
#     "A vibrant city park during autumn, with leaves changing colors, people jogging, walking dogs, and children playing.",
#     "A high-tech control room with large screens displaying data, engineers monitoring systems, and futuristic equipment.",
#     "A magical library with books flying off shelves, enchanted creatures reading, and a grand spiral staircase.",
#     "A close-up of a vintage typewriter with a sheet of paper, keys pressed, and letters forming words.",
#     "A bustling harbor with ships docked, fishermen unloading catch, seagulls flying overhead, and a lighthouse in the distance.",
#     "A serene meadow with wildflowers in bloom, butterflies fluttering, and a mountain range on the horizon.",
#     "A dramatic gladiator arena in ancient Rome, with crowds cheering, and gladiators in the midst of combat.",
#     "A futuristic monorail speeding through a cityscape, elevated tracks, sleek design, and skyscrapers around.",
#     "A tranquil monastery atop a hill, surrounded by clouds, monks tending to gardens, and a sunrise painting the sky.",
#     "An artistic still life of fruit and a wine bottle on a rustic table, with dramatic lighting and shadows.",
#     "A scene of children exploring a magical wardrobe leading to a fantastical world, with wonder on their faces.",
#     "A majestic waterfall in a tropical jungle, rainbow forming in the mist, and exotic animals nearby.",
#     "A night sky filled with shooting stars over a desert landscape, with silhouettes of cacti and a campfire.",
#     "A detailed close-up of an owl perched on a branch at night, eyes glowing, feathers detailed.",
#     "A high-energy Formula 1 race, cars speeding around a curve, motion blur, and crowds in the stands.",
#     "A serene scene of a gondola gliding through Venice's canals, historic buildings on either side, and bridges overhead.",
#     "A futuristic laboratory where scientists are creating holographic projections, advanced technology evident.",
#     "A whimsical treehouse village with multiple levels, rope bridges, and children playing among the branches.",
#     "A historical scene of a Viking ship sailing under the northern lights, warriors on deck, and icy waters.",
#     "A bustling city street in the 1950s, classic cars, people in period clothing, neon signs, and diners.",
#     "A tranquil Japanese garden with a stone lantern, koi pond, and cherry blossoms in bloom.",
#     "An action-packed superhero scene with a hero flying over a cityscape, cape flowing, and villains below.",
#     "A serene mountain cabin with smoke rising from the chimney, pine trees surrounding, and snow-covered peaks.",
#     "A futuristic city with towering skyscrapers connected by sky bridges, drones flying, and greenery integrated into architecture.",
#     "A detailed close-up of a mechanical pocket watch, gears visible through a transparent casing, and hands ticking.",
#     "A dramatic desert scene with towering rock formations, a lone cowboy riding horseback, and a setting sun.",
#     "A bustling newsroom with reporters typing, phones ringing, and headlines being printed.",
#     "A tranquil scene of a sailboat on a lake during sunrise, mist rising, and mountains in the background.",
#     "A high-energy soccer match, a player kicking the ball mid-air towards the goal, with spectators cheering.",
#     "A serene winter night with the full moon illuminating a snowy landscape, and a pack of wolves howling.",
#     "A futuristic transport hub with levitating trains, people in modern attire, and holographic advertisements.",
#     "A detailed illustration of a wizard casting a spell, magical energies swirling, and ancient tomes open around.",
#     "A vibrant underwater scene with dolphins playing, coral reefs, and sunlight creating patterns on the ocean floor.",
#     "A bustling art fair with artists displaying works, visitors strolling, and colorful tents under a clear sky.",
#     "A serene rural landscape with windmills turning, fields of tulips in various colors, and a clear blue sky.",
#     "A dramatic sky filled with hot air balloons during sunset, creating a kaleidoscope of colors.",
#     "A close-up of a chess game in progress, focus on the pieces and the hands of the players, intense concentration.",
#     "A bustling city during a festival, fireworks exploding above skyscrapers, and crowds celebrating below.",
#     "A tranquil farm scene with a red barn, grazing animals, and rolling hills under a partly cloudy sky.",
#     "A high-energy surfing scene with a surfer riding a massive wave, water spraying, and the sun glinting off the ocean.",
#     "A serene night scene of a lighthouse on a cliff, the beacon illuminating the dark sea, and stars filling the sky.",
# ]

# 2560X2560
# prompt_list = [
#     "A majestic lion standing atop a rocky outcrop in the savannah at sunset, with a golden mane blowing in the wind and a pride of lions resting below.",
#     "An intricately designed stained glass window depicting a celestial scene, with vibrant colors casting a kaleidoscope of light into a grand cathedral.",
#     "A bustling medieval marketplace with merchants selling spices and fabrics, townsfolk engaging in trade, and a castle looming in the background.",
#     "A futuristic cityscape at night with flying cars zipping between towering skyscrapers adorned with holographic advertisements.",
#     "A serene waterfall in a lush jungle, with a rainbow formed in the mist and exotic animals like toucans and monkeys in the trees.",
#     "An astronaut floating weightlessly inside a space station, with Earth visible through a large window and equipment panels lining the walls.",
#     "A close-up of a honeybee collecting nectar from a sunflower, with detailed textures of the bee's wings and the flower's petals.",
#     "A winter scene of a frozen lake surrounded by snow-covered pine trees, with ice skaters gliding gracefully under a clear blue sky.",
#     "A dramatic scene of a volcano erupting, lava flowing down the sides, ash clouds billowing upwards, and lightning striking within the plume.",
#     "An underwater cavern illuminated by bioluminescent algae, with divers exploring and schools of glowing fish swimming around.",
#     "A detailed portrait of an elderly man with wrinkles telling a story, wearing a weathered hat, eyes reflecting a life full of experiences.",
#     "A colorful hot air balloon ascending over a patchwork of farmland at sunrise, with other balloons dotting the sky.",
#     "A futuristic robot walking a dog in a park, with people jogging, trees lining the path, and a modern city skyline in the background.",
#     "A close-up of a gourmet dish plated artistically, with vibrant colors, textures, and garnishes, set on a white tablecloth.",
#     "An ancient temple overgrown by the jungle, with roots enveloping stone structures and shafts of light penetrating the canopy.",
#     "A dramatic thunderstorm over a city skyline at night, with bolts of lightning illuminating the skyscrapers and heavy rain falling.",
#     "A whimsical scene of fairies dancing in a moonlit forest clearing, with glowing wings and sparkles of magic in the air.",
#     "A close-up of a glass of red wine being poured, capturing the flow of liquid and reflections on the glass surface.",
#     "A scene of a sailboat navigating through icebergs in polar waters, with penguins on nearby ice floes and a pink sunset sky.",
#     "An action shot of a cyclist racing down a mountain trail, dirt flying, trees blurring in the background, and intense focus on the rider's face.",
#     "A historical scene of a samurai practicing with a katana in a bamboo forest, wearing traditional armor, with leaves gently falling.",
#     "A vibrant city street at night during a festival, with paper lanterns hanging overhead, food stalls, and performers entertaining crowds.",
#     "A serene image of a monk walking across a bridge over a tranquil pond filled with lotus flowers, surrounded by weeping willows.",
#     "A close-up of an eye with a galaxy reflected in the iris, capturing the intricate details and colors of both the eye and the stars.",
#     "A futuristic laboratory with scientists examining a holographic projection of DNA strands, advanced equipment surrounding them.",
#     "A dramatic scene of a firefighter rescuing a kitten from a burning building, flames and smoke providing a stark backdrop.",
#     "An aerial view of a winding river cutting through a dense rainforest, with mist rising and exotic birds flying overhead.",
#     "A bustling open-air market in Africa, with vibrant fabrics, handcrafted goods, and people engaging in lively trade.",
#     "A detailed illustration of a pirate ship battling a kraken at sea, with stormy waves, torn sails, and the creature's tentacles wrapping around the vessel.",
#     "A serene scene of a woman practicing yoga on a cliff overlooking the ocean at sunrise, with waves crashing below.",
#     "A group of friends gathered around a campfire at night, roasting marshmallows, with a starry sky and pine trees surrounding.",
#     "A close-up of a mechanical keyboard with colorful backlighting, fingers typing rapidly, and code displayed on a monitor in the background.",
#     "An underwater scene of a submerged ancient city, with statues and buildings covered in coral and marine life swimming through.",
#     "A futuristic scene of humans and aliens coexisting in a spaceport, with various spacecraft, signs in different languages, and diverse characters interacting.",
#     "A dramatic image of a tornado funnel cloud approaching a farmhouse on the plains, with dark skies and debris swirling.",
#     "A serene orchard in springtime, with fruit trees blossoming, bees pollinating flowers, and a gentle breeze scattering petals.",
#     "A close-up of a musician playing a grand piano on a stage, spotlight illuminating the performer, and audience in silhouette.",
#     "A magical scene of a unicorn drinking from a crystal-clear lake in an enchanted forest, with sparkling light and mystical creatures nearby.",
#     "An industrial landscape at sunset, with silhouettes of factories, smokestacks, and cranes against a colorful sky.",
#     "A detailed illustration of a spaceship cockpit, with an astronaut navigating through an asteroid field, controls and displays glowing.",
#     "A bustling cityscape reflected in the windows of a modern skyscraper, creating an abstract mosaic of urban life.",
#     "A group of dancers performing traditional folk dance in colorful costumes, captured mid-movement with joyful expressions.",
#     "A serene beach scene at night, with bioluminescent plankton causing the waves to glow, and a full moon illuminating the shoreline.",
#     "A dramatic action scene of a secret agent rappelling down the side of a building at night, city lights below, and helicopters overhead.",
#     "A close-up of a chessboard during a tense match, focus on the queen piece, with reflections on the polished surface.",
#     "A whimsical illustration of a tree with doors and windows, inhabited by woodland creatures, with lanterns hanging from branches.",
#     "A detailed portrait of a Native American chief wearing a traditional headdress, with intricate beadwork and feathers.",
#     "An aerial view of a bustling port city, with ships docked, cranes unloading cargo, and a network of roads and buildings.",
#     "A serene mountain landscape reflected perfectly in a still lake, with wildflowers in the foreground and a clear sky.",
#     "A futuristic scene of a hoverboard race through a neon-lit city, competitors wearing sleek gear, and crowds watching from platforms.",
#     "A close-up of a cat lounging in a sunbeam, eyes half-closed, whiskers twitching, and soft fur detailed.",
#     "An action-packed scene of a dragon breathing fire while soaring over a medieval village, with villagers reacting below.",
#     "A peaceful countryside cottage surrounded by a garden in full bloom, with a cobblestone path and smoke rising from the chimney.",
#     "A group of astronauts exploring the surface of an alien planet, strange rock formations, and a large ringed planet in the sky.",
#     "A dynamic image of a basketball player making a slam dunk in a street court, graffiti on the walls, and spectators cheering.",
#     "A detailed still life of vintage musical instruments, including a violin, trumpet, and sheet music, arranged artistically.",
#     "A serene image of a lighthouse standing guard on a cliff during a calm sunrise, waves gently crashing below.",
#     "A bustling urban street food market at night, with steam rising from stalls, vibrant signs, and people enjoying diverse cuisines.",
#     "A close-up of a watchmaker repairing a mechanical watch, tiny gears and tools on a workbench under a magnifying glass.",
#     "An ethereal scene of a dancer underwater, fabric flowing around, bubbles rising, and light filtering from above.",
#     "A futuristic soldier in advanced armor standing on a battlefield, with robots and drones in the background.",
#     "A tranquil scene of a horse grazing in a meadow during golden hour, with rolling hills and a wooden fence.",
#     "A dramatic image of a surfer riding a massive wave, water spraying, and the sun setting on the horizon.",
#     "A close-up of a butterfly emerging from a chrysalis on a branch, wings unfolding, with a blurred background.",
#     "An aerial view of a labyrinthine city with winding streets, canals, and bridges, reminiscent of Venice.",
#     "A detailed illustration of a knight kneeling before a king in a grand throne room, with banners and stained glass windows.",
#     "A serene image of a sailboat drifting on a foggy lake at dawn, with silhouettes of trees and gentle ripples.",
#     "A bustling cyberpunk alleyway with neon signs, rain-soaked streets, and characters in futuristic attire.",
#     "A close-up of a hand holding a glowing orb, with mystical symbols floating around and a dark background.",
#     "An action scene of firefighters battling a blazing forest fire, flames towering, and helicopters dropping water.",
#     "A tranquil Japanese tea ceremony taking place in a traditional room with tatami mats and shoji screens.",
#     "A dramatic image of a race car speeding around a track, motion blur conveying speed, and crowds in the stands.",
#     "A whimsical scene of balloons lifting a small house into the sky, floating above mountains and clouds.",
#     "A detailed portrait of a woman wearing traditional Indian attire, with intricate henna designs on her hands.",
#     "A serene night sky over a mountain range, with the Milky Way visible and a shooting star streaking across.",
#     "An action shot of a soccer player taking a penalty kick, goalkeeper ready to dive, and stadium lights bright.",
#     "A close-up of a vintage camera held by a photographer, with focus on the lens and hands adjusting settings.",
#     "A futuristic monorail gliding through a city with greenery integrated into buildings, passengers enjoying the view.",
#     "An ethereal forest scene with trees whose leaves glow softly, a pathway leading into the distance, and mist hovering.",
#     "A dramatic image of a boxer in the ring between rounds, sitting on a stool, sweat glistening, and coach giving advice.",
#     "A tranquil farm scene at sunrise, with tractors in the fields, barns in the background, and animals starting their day.",
#     "A whimsical illustration of a child reading a book, with story characters coming to life around them.",
#     "A detailed image of a glassblower creating a delicate piece, molten glass glowing, and tools scattered on a workbench.",
#     "An action-packed scene of a superhero landing on a rooftop, cape billowing, with a cityscape behind.",
#     "A serene image of an old steam locomotive traveling through a snowy landscape, smoke trailing into the sky.",
#     "A close-up of a blacksmith's hands forging metal on an anvil, sparks flying, and intense focus.",
#     "A futuristic underwater hotel with large windows showing marine life, guests dining and enjoying the view.",
#     "An aerial view of terraced rice fields in Asia, with farmers working and reflections of the sky in the water.",
#     "A dramatic scene of a spaceship entering warp speed, stars stretching into streaks, and planets fading behind.",
#     "A peaceful image of a swan gliding across a calm pond at sunset, with reeds and lily pads.",
#     "A detailed illustration of a treasure map with mountains, forests, and an X marking the spot, aged parchment texture.",
#     "An action shot of a snowboarder performing a jump in the mountains, snow flying, and clear blue sky.",
#     "A close-up of a violinist playing passionately on stage, with focus on the strings and bow movement.",
#     "A serene desert landscape at night, with towering sand dunes under a star-filled sky and a crescent moon.",
#     "A bustling city square in winter with a Christmas market, decorated trees, and people enjoying festive activities.",
#     "A futuristic scene of a colony ship traveling through space, massive engines, and cryogenic pods visible.",
#     "An ethereal image of a dancer surrounded by swirling fabric and light trails, creating a sense of motion.",
#     "A dramatic scene of a pirate captain standing on the deck of a ship during a storm, waves crashing.",
#     "A tranquil image of a cottage by a lake in autumn, with trees displaying fall colors and leaves falling.",
#     "A detailed illustration of a dragon curled around a pile of gold in a cavern, scales reflecting torchlight.",
#     "An action-packed image of a marathon runner crossing the finish line, crowds cheering, and determination on their face.",
#     "A close-up of a scientist looking through a microscope in a lab, with equipment and notes in the background.",
#     "A serene image of a couple dancing under the moonlight on a beach, footprints in the sand, gentle waves.",
#     "A futuristic scene of robots playing chess in a park, with humans observing and nature integrated into the setting.",
#     "A dramatic image of a wildfire with firefighters silhouetted against the flames, smoke filling the sky.",
#     "An aerial view of a city at night with streets illuminated, forming a network of lights, and skyscrapers towering.",
#     "A tranquil scene of a hot spring in a snowy landscape, with steam rising and people relaxing in the water.",
#     "A whimsical illustration of animals having a tea party in the forest, dressed in clothes, with a table set elegantly.",
#     "A detailed image of an antique globe in a study, with old books, quill pen, and candlelight.",
#     "An action shot of a hockey player taking a slapshot on the ice rink, puck in motion, and stadium lights.",
#     "A serene image of cherry blossoms framing a traditional Japanese pagoda reflected in a pond.",
#     "A close-up of a hand writing calligraphy with a fountain pen on parchment, ink flowing smoothly.",
#     "A futuristic city built on floating islands in the sky, connected by bridges, with airships moving between them.",
# ]

# 2048x2048
# prompt_list = [
#     "A tranquil mountain meadow at sunrise, with wildflowers in bloom and a herd of deer grazing peacefully.",
#     "An intricate mandala design with vibrant colors and complex geometric patterns.",
#     "A futuristic robot chef preparing a meal in a high-tech kitchen, with holographic recipe displays.",
#     "A detailed close-up of a ladybug crawling on a leaf covered in morning dew, with fine details of its wings and spots.",
#     "An ancient underwater city with coral-covered ruins, and marine life swimming through the structures.",
#     "A bustling medieval village market square, with merchants selling goods, villagers in period attire, and a castle in the background.",
#     "A serene autumn forest scene with a carpet of fallen leaves, sunbeams filtering through the trees, and a narrow path leading into the distance.",
#     "An astronaut exploring the surface of Mars, with the red rocky landscape stretching out under a pinkish sky.",
#     "A high-energy concert scene with a DJ performing on stage, laser lights cutting through the air, and a crowd dancing.",
#     "A steampunk-inspired mechanical dragon flying over a Victorian-era city, with steam-powered vehicles on the streets below.",
#     "A peaceful beach at sunset with a hammock tied between two palm trees, gentle waves lapping the shore, and seagulls flying overhead.",
#     "A futuristic courtroom with robotic judges, holographic evidence displays, and lawyers presenting cases.",
#     "A close-up of a snowflake on a person's glove, showing the intricate crystalline structure in sharp detail.",
#     "An enchanted library where books are floating in mid-air, pages turning themselves, and magical symbols glowing.",
#     "A detailed illustration of a medieval map showing mythical lands, sea monsters, and ornate compass roses.",
#     "A bustling farmer's market with stalls selling fresh produce, flowers, and handmade crafts, people mingling and shopping.",
#     "A serene nighttime scene of fireflies illuminating a meadow, with a clear starry sky and a crescent moon above.",
#     "A dynamic action shot of a motocross rider performing a mid-air trick over dirt ramps, dust particles visible.",
#     "A whimsical treehouse village connected by rope bridges, nestled high in the branches of ancient trees.",
#     "An ice castle glowing under the northern lights, with intricate ice sculptures and a frozen moat.",
#     "A close-up of a glass of lemonade with ice cubes and mint leaves, condensation droplets forming on the glass.",
#     "A futuristic scientist working in a lab with floating chemical beakers, touch-screen interfaces, and robotic assistants.",
#     "A vibrant carnival parade with performers in elaborate costumes, colorful floats, and confetti raining down.",
#     "A serene koi pond in a Japanese garden, with fish swimming gracefully, lily pads, and a small arched bridge.",
#     "An ancient warrior standing atop a hill, clad in ornate armor, with a vast battlefield stretching out behind.",
#     "A detailed close-up of a peacock's feathers, showcasing the vibrant colors and eye-like patterns.",
#     "A bustling spaceport on an alien planet, with diverse extraterrestrial species, spacecraft landing and taking off.",
#     "A tranquil scene of a windmill turning slowly in a field of tulips, with a clear blue sky and fluffy clouds.",
#     "A dynamic image of a basketball player shooting a three-pointer, the ball mid-air, and the crowd holding their breath.",
#     "A steampunk-inspired clock tower with exposed gears and steam vents, set against a cloudy sky.",
#     "A serene underwater scene of a mermaid sitting on a rock, surrounded by colorful fish and coral reefs.",
#     "A futuristic city park with hovering benches, holographic art installations, and people enjoying nature.",
#     "A close-up of a chef expertly slicing vegetables in a professional kitchen, motion blur on the knife.",
#     "An enchanted forest with trees whose leaves glow softly, mystical creatures peeking from behind trunks.",
#     "A high-energy surfing competition with surfers riding massive waves, spectators watching from the beach.",
#     "A detailed illustration of a dragon guarding a hoard of treasure in a dimly lit cavern.",
#     "A peaceful image of a panda eating bamboo in a lush forest, with dappled sunlight filtering through the trees.",
#     "A bustling airport terminal of the future, with transparent walkways, flying vehicles, and digital signage.",
#     "A dramatic scene of a knight battling a giant troll on a stone bridge over a raging river.",
#     "A serene desert oasis with palm trees, a clear pool of water, and camels resting nearby.",
#     "A close-up of a vinyl record spinning on a turntable, the needle gliding along the grooves.",
#     "An action-packed scene of a spaceship engaging in a dogfight with enemy ships amidst asteroid fields.",
#     "A tranquil scene of a lighthouse on a rocky coastline during a foggy morning, waves crashing below.",
#     "A futuristic fashion show with models wearing avant-garde designs, holographic fabrics, and robotic elements.",
#     "A detailed illustration of a magic spellbook with ancient runes, glowing symbols, and pages turning themselves.",
#     "A bustling cityscape at dawn, with commuters starting their day, skyscrapers reflecting the sunrise.",
#     "A peaceful meadow with horses grazing, wildflowers in bloom, and a wooden fence running along a dirt path.",
#     "An action shot of a snowboarder performing a trick off a snowy ramp, mountains in the background.",
#     "A whimsical bakery storefront with colorful pastries displayed, a striped awning, and a cobblestone street.",
#     "A serene image of a sailboat navigating through crystal-clear waters, tropical islands visible in the distance.",
#     "A close-up of a person's hands playing an acoustic guitar, strings vibrating, and natural light illuminating the scene.",
#     "An ancient temple interior with towering pillars, intricate carvings, and beams of light shining down.",
#     "A dynamic soccer match moment capturing a goalkeeper making a diving save, ball inches from gloves.",
#     "A futuristic underwater research facility with large windows showing marine life, scientists conducting experiments.",
#     "A tranquil forest clearing with a small waterfall feeding into a pond, surrounded by lush vegetation.",
#     "A dramatic scene of a superhero flying over a city skyline at dusk, cape flowing, and buildings below.",
#     "A detailed illustration of a phoenix rising from its ashes, vibrant flames and feathers depicted.",
#     "A bustling marketplace on an alien planet, with exotic goods, diverse creatures, and strange architecture.",
#     "A serene winter landscape with a horse-drawn sleigh moving through snow-covered trees, gentle snowfall.",
#     "A close-up of an artist's palette filled with mixed paint colors, brushes lying nearby, and a canvas in the background.",
#     "An action-packed car chase through city streets, with vehicles weaving through traffic and helicopters overhead.",
#     "A peaceful image of a swan gliding across a misty lake at sunrise, with reeds and lilies along the shore.",
#     "A futuristic classroom with students learning through holographic displays, robotic assistants aiding instruction.",
#     "A dramatic volcanic landscape with rivers of lava, ash clouds, and a silhouetted figure observing from a distance.",
#     "A whimsical scene of balloons carrying a cluster of small houses into the sky, floating over a lush landscape.",
#     "A detailed close-up of a gemstone reflecting light, showing internal facets and vibrant colors.",
#     "A bustling harbor at dawn, with fishing boats returning, seagulls flying, and the sun rising over the water.",
#     "A serene image of a yoga class practicing on a beach at sunset, silhouettes against the colorful sky.",
#     "An action scene of a medieval battle with knights charging, archers releasing arrows, and banners flying.",
#     "A futuristic medical facility with advanced technology, doctors using holographic displays to diagnose patients.",
#     "A tranquil garden maze with tall hedges, a fountain at the center, and people wandering the paths.",
#     "A close-up of a glass teapot with blooming tea inside, steam rising and sunlight filtering through.",
#     "An enchanted moonlit forest with glowing flowers, a unicorn drinking from a stream, and stars twinkling above.",
#     "A dynamic image of a baseball player hitting a home run, the ball soaring towards the stadium lights.",
#     "A steampunk-inspired laboratory with Tesla coils, mechanical devices, and scientists in Victorian attire.",
#     "A peaceful scene of hot air balloons drifting over a vineyard during harvest season, grapes ripe on the vines.",
#     "An action-packed image of a firefighter rescuing people from a burning building, flames and smoke intensifying.",
#     "A futuristic train speeding through a countryside, levitating above the tracks, and mountains in the background.",
#     "A detailed illustration of an enchanted castle with spires reaching into the clouds, surrounded by a magical forest.",
#     "A serene lakeside campsite with a tent pitched near the water, campfire crackling, and stars reflecting on the lake.",
#     "A bustling cyberpunk street market with neon lights, rain-soaked streets, and characters in futuristic attire.",
#     "A close-up of a violin being played, focus on the strings and bow, with soft lighting highlighting the wood grain.",
#     "An action scene of a parkour athlete leaping between buildings in an urban environment, motion blur conveying speed.",
#     "A peaceful image of a mother elephant walking with her calf across the savannah, acacia trees dotting the landscape.",
#     "A dynamic roller coaster ride captured mid-loop, riders' expressions of excitement, and a theme park in the background.",
#     "A detailed illustration of a magical potion shop filled with bubbling cauldrons, shelves of ingredients, and spellbooks.",
#     "A serene Japanese tea garden with a stone path, cherry blossoms in bloom, and a small waterfall.",
#     "An action-packed sci-fi battle scene with mechs fighting in a futuristic city, explosions and lasers lighting up the scene.",
#     "A close-up of a sunflower field, focus on a single sunflower with bees collecting pollen, under a bright blue sky.",
#     "A tranquil image of a child blowing dandelion seeds in a meadow, with soft focus on floating seeds.",
#     "A dramatic image of a stormy sea with a ship navigating through towering waves, dark clouds overhead.",
#     "A bustling art studio with artists painting, sculptures in progress, and canvases lining the walls.",
#     "A serene image of a wolf standing on a rocky outcrop under the full moon, howling into the night.",
#     "An action scene of a skateboarding trick in an urban skate park, graffiti-covered walls, and spectators watching.",
#     "A detailed illustration of a fantasy map showing kingdoms, mountains, and mythical creatures.",
#     "A peaceful image of a cat napping in a sunbeam on a windowsill, with plants and curtains framing the scene.",
#     "A dynamic image of a tennis player serving the ball, focus on form and intensity, spectators blurred in the background.",
#     "A futuristic city floating in the sky, with airships docking, waterfalls cascading from platforms.",
#     "A close-up of a crystal ball on a wooden table, with mystical smoke swirling inside and tarot cards nearby.",
#     "An action-packed pirate ship battle on the high seas, cannons firing, sails billowing, and swords clashing.",
#     "A serene image of a person meditating on a cliff overlooking the ocean at sunrise, peaceful and contemplative.",
#     "A bustling open-air theater performance in a park, actors on stage, audience seated on the grass, fairy lights strung above.",
#     "A dramatic image of a meteor shower over a desert landscape, with cacti silhouetted against the starry sky.",
#     "A whimsical bakery kitchen with anthropomorphic animals baking pastries, flour dust in the air.",
#     "A detailed illustration of a time machine with dials, levers, and a glowing core, set in a Victorian-era workshop.",
#     "A tranquil scene of a narrowboat traveling down a canal lined with weeping willows and quaint cottages.",
#     "An action shot of a fencing match, two fencers lunging at each other, focus on their swords and footwork.",
#     "A close-up of a honeycomb dripping with honey, bees working diligently, golden hues and textures highlighted.",
#     "A peaceful image of a garden patio with a wrought-iron table set for tea, climbing roses on a trellis.",
#     "A dynamic image of a BMX biker performing a backflip over dirt ramps, dust and excitement in the air.",
#     "A steampunk airship docking at a floating city, with intricate mechanical details and characters in period attire.",
#     "A serene winter scene of a frozen waterfall, icicles hanging, and snow-covered trees surrounding.",
#     "An action-packed scene of a space explorer escaping an alien creature in a dense extraterrestrial jungle.",
#     "A detailed illustration of a celestial compass with zodiac symbols, stars, and intricate engravings.",
#     "A tranquil image of a dolphin leaping out of the water at sunset, droplets sparkling, and horizon glowing.",
#     "A bustling marketplace in a desert city, with colorful fabrics draped over stalls, spices piled high, and lively trade.",
#     "A dramatic scene of a volcano erupting under a night sky, lava illuminating the landscape, and stars above.",
#     "A whimsical image of an enchanted forest where the trees have faces and woodland creatures gather for a meeting.",
#     "A close-up of a pianist's hands playing a grand piano, keys in sharp focus, stage lights softly illuminating.",
#     "An action scene of a car racing video game screenshot, high-speed cars on a futuristic track, vibrant graphics.",
#     "A peaceful image of a family picnicking in a park, children playing, a dog fetching a frisbee, and trees providing shade.",
#     "A dynamic image of a ballerina performing a pirouette on stage, spotlight focused, audience in darkness.",
#     "A detailed illustration of a haunted house on a hill, with twisted trees, full moon, and bats flying.",
#     "A serene scene of a fisherman casting a line in a misty river at dawn, reflections on the water.",
# ]

# 2048x1024
prompt_list = [
    "A panoramic view of a bustling city skyline at sunset, with skyscrapers silhouetted against a colorful sky.",
    "A serene beach scene with waves gently crashing on the shore, palm trees swaying, and a sailboat on the horizon.",
    "A vast desert landscape with sand dunes stretching into the distance under a clear, starry night sky.",
    "A mountain range with snow-capped peaks reflecting in a calm alpine lake, surrounded by evergreen forests.",
    "A futuristic city with flying cars moving between towering skyscrapers adorned with neon lights.",
    "A panoramic shot of the Milky Way galaxy arching over a peaceful countryside at night.",
    "A busy marketplace in an exotic city, with colorful stalls, people shopping, and vibrant decorations.",
    "A fleet of hot air balloons rising over a picturesque valley during sunrise, with mist in the lowlands.",
    "An expansive field of sunflowers facing the morning sun, with a rustic farmhouse in the background.",
    "A panoramic view of the Great Wall of China winding across mountains under a bright blue sky.",
    "A futuristic space station orbiting Earth, with astronauts performing a spacewalk and Earth visible below.",
    "A coastal cliffside with waves crashing against the rocks, a lighthouse standing tall, and seabirds flying.",
    "A bustling harbor with ships docked, cranes loading cargo, and a city skyline in the background.",
    "A tranquil Japanese garden with a winding path, koi pond, and cherry blossom trees in full bloom.",
    "A panoramic view of a medieval castle overlooking a village, with rolling hills and farmland beyond.",
    "A forest in autumn with trees displaying brilliant red, orange, and yellow leaves, and a winding river.",
    "A race track with cars speeding by, motion blur conveying speed, and cheering crowds in the stands.",
    "A wide shot of a music festival crowd at night, with stage lights illuminating the audience.",
    "An underwater scene of a coral reef teeming with colorful fish, sea turtles, and rays of sunlight penetrating the water.",
    "A herd of wild horses running across an open plain, dust kicked up behind them, mountains in the distance.",
    "A panoramic aerial view of rice terraces cascading down a hillside in a rural Asian landscape.",
    "A serene lake at dusk with kayakers paddling, reflections of the sunset on the water, and forested shores.",
    "A sprawling vineyard with grapevines neatly lined up, a winery in the background, and hills beyond.",
    "A bustling street in a European city, with cafes, pedestrians, street musicians, and historic architecture.",
    "A safari scene with zebras and giraffes grazing on the savannah under a bright African sun.",
    "A panoramic shot of a fireworks display over a city skyline, reflections glittering on a river below.",
    "A futuristic underwater city with domed habitats connected by transparent tunnels, marine life swimming around.",
    "A snowy landscape with a frozen river, pine trees covered in snow, and a small cabin with smoke rising from the chimney.",
    "A carnival scene with a Ferris wheel, colorful rides, game booths, and people enjoying the festivities.",
    "A panoramic view of a mountain road winding through rugged terrain, with motorcyclists riding along.",
    "A battlefield scene from ancient times, with armies facing off, banners flying, and dramatic skies.",
    "A night sky filled with northern lights over a calm lake, stars reflecting on the water's surface.",
    "A bustling airport runway with planes taking off and landing, ground crew working, and terminals in the background.",
    "A wide shot of a rainforest canopy from above, with mist rising and exotic birds flying over the treetops.",
    "A futuristic city park with greenery, people relaxing, and innovative architecture blending with nature.",
    "A panoramic view of an art gallery interior, with visitors admiring paintings and sculptures displayed along wide walls.",
    "An open highway stretching into the desert, with a classic convertible driving along, mountains in the background.",
    "A sports stadium filled with fans during a big game, players on the field, and bright lights illuminating the scene.",
    "A harbor at sunrise with fishing boats heading out to sea, the sky painted with warm colors.",
    "A panoramic shot of ancient ruins in a desert, with sandstone structures and archaeologists exploring.",
    "A winter landscape with skiers descending a mountain slope, snow-covered trees, and a ski lodge below.",
    "A wide shot of a parade marching down a city street, with floats, marching bands, and spectators lining the sidewalks.",
    "A panoramic view of the Grand Canyon, showcasing layered rock formations and the winding river below.",
    "A sunset over a lavender field in bloom, with rows of purple flowers extending to the horizon.",
    "A group of surfers catching waves at a famous beach, with a dramatic sky and cliffs in the background.",
    "An outdoor concert in a natural amphitheater, musicians performing on stage, and an audience seated on grassy slopes.",
    "A panoramic image of a city's skyline reflected in the calm waters of a river at night.",
    "A scene of hot springs and geysers erupting in a geothermal area, with steam clouds and colorful mineral deposits.",
    "A wide shot of a roller coaster in an amusement park, riders screaming as they go through loops and drops.",
    "A festival of lanterns being released into the night sky over a lake, their warm glow reflected on the water.",
    "A panoramic view of a sunflower field under a clear sky, with bees buzzing and a rustic barn in the distance.",
    "A train winding through a mountain pass, smoke billowing from the engine, with majestic peaks surrounding.",
    "A harbor during a sailing regatta, numerous sailboats with colorful sails racing across the water.",
    "An aerial view of a maze-like city with narrow streets and rooftops close together, reminiscent of a Mediterranean town.",
    "A desert scene with a caravan of camels crossing the sand dunes, with a mirage shimmering in the distance.",
    "A panoramic view of a glacier-fed river cutting through a valley, with ice-capped mountains and wildflowers.",
    "A busy street market in India, with vibrant fabrics, spices, street food vendors, and bustling crowds.",
    "A coastal road along a rugged shoreline, waves crashing against cliffs, and a classic car driving along.",
    "A panoramic shot of a historic battlefield reenactment, with participants in period costumes and smoke from cannons.",
    "A tropical island beach with turquoise waters, palm trees, and a hammock strung between two trees.",
    "A panoramic view of a futuristic spaceport, with spacecraft taking off, aliens and humans interacting.",
    "A nighttime scene of a city under a full moon, with lights glowing in windows and stars visible above.",
    "A wide shot of an agricultural landscape with patchwork fields, farmhouses, and tractors working the land.",
    "A panoramic view of a waterfall cascading over cliffs into a river, with a rainbow forming in the mist.",
    "A city street at night after rain, with reflections of neon signs on wet pavement and people with umbrellas.",
    "A wide shot of a soccer stadium during a match, players in action, and fans waving flags.",
    "A harbor scene at sunset with tall ships docked, sails furled, and masts silhouetted against the sky.",
    "A panoramic view of a theme park with roller coasters, Ferris wheels, and crowds enjoying the attractions.",
    "A beach scene with families building sandcastles, children playing, and surfers in the distance.",
    "A wide shot of a forest fire being fought by firefighters, with flames and smoke rising into the sky.",
    "A desert night scene with a campfire surrounded by tents, people stargazing under a clear sky.",
    "An expansive field of tulips in full bloom, with workers harvesting flowers and windmills in the background.",
    "A panoramic view of an old European city with a river running through it, bridges crossing, and historic buildings.",
    "A busy highway interchange at night, with streaks of light from cars and towering overpasses.",
    "A harbor scene with yachts and luxury boats, people walking along the docks, and restaurants overlooking the water.",
    "A panoramic view of a mountain meadow with wildflowers, a wooden fence, and grazing cattle.",
    "A scene of a space shuttle launching, flames and smoke billowing, with spectators watching from a safe distance.",
    "A cityscape with skyscrapers emerging from fog or low clouds, the tops of buildings visible above the mist.",
    "A wide shot of a wind farm with rows of wind turbines spinning, set against a backdrop of rolling hills.",
    "A panoramic image of a snowy landscape with northern lights overhead, reflecting on a frozen lake.",
    "A vineyard during autumn with leaves turning colors, grape harvest in progress, and barrels being filled.",
    "A scene of a medieval festival with jousting tournaments, people in period costumes, and colorful tents.",
    "A panoramic view of a mountain village nestled in a valley, smoke rising from chimneys, and snow-capped peaks.",
    "An underwater panorama of a shipwreck being explored by divers, schools of fish swimming around.",
    "A coastal scene with a boardwalk, amusement rides, people strolling, and the ocean waves beside.",
    "A panoramic shot of an open-pit mine, heavy machinery working, and terraced layers of earth exposed.",
    "A city street during a heavy snowstorm, cars covered in snow, and people bundled up walking.",
    "A scene of a marathon race in a city, runners passing landmarks, spectators cheering along the route.",
    "A panoramic view of a harbor at night with cruise ships docked, city lights reflecting on the water.",
    "A beach sunset with silhouetted figures doing yoga or meditation, calm sea, and colorful sky.",
    "A scene of a science fair with students displaying projects, judges evaluating, and enthusiastic onlookers.",
    "A panoramic view of an airport terminal interior, passengers walking, planes visible through large windows.",
    "A meadow with wild horses grazing under a dramatic sky with storm clouds approaching.",
    "A city skyline at dawn, with skyscrapers catching the first light, and a river flowing through.",
    "A panoramic shot of a glacier with ice caves and hikers exploring the icy landscape.",
    "A scene of a street festival with food trucks, live music, and people dancing.",
    "A wide shot of a train traveling through a snowy landscape, steam billowing, and winter trees alongside.",
    "A panoramic view of a tropical rainforest canopy with waterfalls and exotic birds flying above.",
    "A scene of a soccer field with children playing, parents watching, and mountains in the background.",
    "A beach scene at night with a bonfire, people gathered around, and the moon reflecting on the ocean.",
    "A panoramic view of a vast canyon with a river winding through it, layers of rock visible in the cliffs.",
    "A bustling market street in Morocco, with colorful rugs hanging, spices displayed, and lanterns overhead.",
    "A wide shot of a race track with horses galloping towards the finish line, spectators cheering.",
    "A panoramic image of an autumn forest reflected in a calm lake, with mist rising in the morning light.",
    "A scene of a farm during harvest season, combines working the fields, and grain silos in the background.",
    "A cityscape at night with fireworks lighting up the sky, reflections on the river, and crowds celebrating.",
    "A panoramic view of a medieval bridge over a river, with old stone buildings lining the banks.",
    "A coastal scene with cliffs, sea stacks, and waves crashing, seabirds nesting on the rocks.",
    "A wide shot of a desert landscape with rock formations, cacti, and a setting sun casting long shadows.",
    "A scene of a music festival in a forest, with stages among the trees and people enjoying the atmosphere.",
    "A panoramic view of a wildlife reserve with elephants, lions, and other animals roaming freely.",
    "A city street lined with cherry blossom trees in full bloom, petals falling, and people enjoying the sight.",
    "A wide shot of a mountain bike trail through dense woods, riders navigating jumps and turns.",
    "A panoramic image of a historic palace with manicured gardens, fountains, and ornate architecture.",
    "A scene of an outdoor yoga class in a park, participants stretching, and a serene environment.",
    "A panoramic view of a harbor city during a festival, with boats illuminated and fireworks overhead.",
    "A scene of an old train station with steam engines, vintage signs, and passengers in period attire.",
    "A wide shot of an ice skating rink in a city square during winter, lights strung overhead.",
    "A panoramic view of a field of poppies in bloom under a clear sky, with mountains in the background.",
    "A scene of a group hiking along a coastal cliff path, ocean waves below, and birds soaring above.",
    "A wide shot of a city skyline at sunset, with reflections on water and clouds painted with warm hues.",
]

# python3 run_multi.py --gpu 5 --gpu_offset 4
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run multiple ScaleCrafter instances in parallel")
    parser.add_argument("--gpu", default="0", type=str, help="GPU id")
    parser.add_argument("--gpu_offset", default=0, type=int, help="GPU offset")
    parser.add_argument("--num_gpus", default=4, type=int, help="Number of GPUs")
    parser.add_argument("--run_file", default="inference/test_t2i.py", type=str, help="File to run")
    parser.add_argument("--width", type=int, default=2048, help="image width")
    parser.add_argument("--height", type=int, default=1024, help="image height")
    parser.add_argument("--num_image", type=int, default=1, help="how many images generated")
    args = parser.parse_args()

    # Download models
    safetensor_url_list = []
    with open("models/models_checklist.txt", "r") as f:
        safetensor_url_list = f.readlines()[:-1]
    safetensor_url_list = [s.strip() for s in safetensor_url_list]
    safetensor_list = [s.split("/")[-1] for s in safetensor_url_list]

    for i, safetensor_name in enumerate(safetensor_list):
        if not os.path.exists(f"models/{safetensor_name}"):
            os.system(f"wget {safetensor_url_list[i]} -O models/{safetensor_name}")

    # Set GPUs
    seed = 2024
    gpu_id = int(args.gpu)
    num_prompts = int(len(prompt_list) // args.num_gpus)
    prompt_list = prompt_list[num_prompts * (gpu_id - args.gpu_offset) : num_prompts * (gpu_id - args.gpu_offset + 1)]

    logging_dir = f"{args.width}x{args.height}"
    cmd_list = []
    for i, prompt in enumerate(prompt_list):
        cmd = f"CUDA_VISIBLE_DEVICES={gpu_id}"
        cmd += f" python {args.run_file}"
        cmd += f" --height {args.height}"
        cmd += f" --width {args.width}"
        cmd += f" --output_dir {logging_dir}"
        cmd += f' --prompt "{prompt}"'
        cmd += f" --num_image {args.num_image}"
        cmd += f" --seed {seed}"
        cmd_list.append(cmd)

    total_cmds = len(cmd_list)
    for i, cmd in enumerate(cmd_list):
        print(f"==== Running command {i+1}/{total_cmds}: {cmd}")
        os.system(cmd)
        # process = subprocess.Popen([cmd], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
        # stdout, stderr = process.communicate()
        # exit_code = process.wait()

        # if exit_code != 0:
        #     raise Exception(f"==== command failed: {arg}, exit_code: {exit_code}, stderr: {stderr}, stdout: {stdout}")
